basePath: /
host: localhost:8080
info:
  contact:
    email: dianerieck@hotmail.com
    name: Diane Elo Rieck
    url: http://www.dianerieck.com.br
  description: Product API with authentication.
  license:
    name: Diane Rieck Licence
    url: http://www.dianerieck.com.br
  termsOfService: http://swagger.io/terms/
  title: Go Expert Example API
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
